name: Terraform Plan

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Initialise Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          tflint --init
          tflint --format sarif > tflint.sarif
        continue-on-error: true

      - name: Upload TFlint sarif results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'terraform/tflint.sarif'
          wait-for-processing: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform
          output_format: cli,sarif
          output_file_path: console,checkov.sarif
        continue-on-error: true

      - name: Upload Checkov sarif results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif
          wait-for-processing: true
